name: my_new_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_speed_dial: ^6.2.0
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.11.0
  flutter_styled_toast: ^2.1.3
  another_flushbar: ^1.12.29
  carousel_slider: ^4.2.1
  expansion_tile_card: ^2.0.0
  marquee: ^2.2.3
  image_picker: ^0.8.6
  flutter_colorpicker: ^1.0.3
  percent_indicator: ^4.2.2
  easy_splash_screen: ^1.0.4
  page_view_dot_indicator: ^2.1.0
  google_nav_bar: ^5.0.6
  flutter_screenutil: ^5.6.0
  get: ^4.6.5
  provider: ^6.0.5
  dio: ^4.0.6
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/BMI logo/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
