// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxIdrP3zWu0xf2Ejp6zON-qKbFoi45XFc',
    appId: '1:1095057392506:web:c12a730e5b5254802f8cc3',
    messagingSenderId: '1095057392506',
    projectId: 'test-train-6dd3e',
    authDomain: 'test-train-6dd3e.firebaseapp.com',
    storageBucket: 'test-train-6dd3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CTQCoJec8sErnY51tELJ5mw9XvBXCSA',
    appId: '1:1095057392506:android:26f3d2061f40b3162f8cc3',
    messagingSenderId: '1095057392506',
    projectId: 'test-train-6dd3e',
    storageBucket: 'test-train-6dd3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzo9DPIRbS2NUAx84Bv8VQcHLrMkqBZo',
    appId: '1:1095057392506:ios:3e67bb65423def6d2f8cc3',
    messagingSenderId: '1095057392506',
    projectId: 'test-train-6dd3e',
    storageBucket: 'test-train-6dd3e.appspot.com',
    iosClientId: '1095057392506-fgk7ak4if645ov10ps7gkh3mbij7pun7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzo9DPIRbS2NUAx84Bv8VQcHLrMkqBZo',
    appId: '1:1095057392506:ios:3e67bb65423def6d2f8cc3',
    messagingSenderId: '1095057392506',
    projectId: 'test-train-6dd3e',
    storageBucket: 'test-train-6dd3e.appspot.com',
    iosClientId: '1095057392506-fgk7ak4if645ov10ps7gkh3mbij7pun7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewApp',
  );
}
